# Generated by Django 3.0.5 on 2020-05-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0005_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='featured_photo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
