# Generated by Django 3.0.5 on 2020-05-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0007_auto_20200516_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='latitude',
            field=models.FloatField(default=27.7089559),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gym',
            name='longitude',
            field=models.FloatField(default=85.2911131),
            preserve_default=False,
        ),
    ]
